// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ReservationTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;

    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }

    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void TC8()
    {
        driver.Navigate().GoToUrl("https://automationintesting.online/");
        driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
        driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
        driver.FindElement(By.CssSelector("button:nth-child(3)")).Click();
        {
            var dragged = driver.FindElement(By.XPath("//button[text()=\'02\']"));
            var dropped = driver.FindElement(By.XPath("//button[text()=\'16\']"));
            Actions builder = new Actions(driver);
            builder.DragAndDrop(dragged, dropped).Perform();
        }
        Thread.Sleep(2000);
        driver.FindElement(By.Name("firstname")).Click();
        driver.FindElement(By.Name("firstname")).SendKeys("Test");
        driver.FindElement(By.Name("lastname")).SendKeys("Test");
        driver.FindElement(By.Name("email")).SendKeys("test@test.com");
        driver.FindElement(By.Name("phone")).SendKeys("aaabbbcccddd");
        driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
        var successButton = driver.FindElement(By.CssSelector(".btn:nth-child(1)"));
        successButton.Click();
        Thread.Sleep(4000);
        var success = driver.FindElement(By.CssSelector(".alert"));
        Thread.Sleep(4000);
    }

    [Test]
    public void TC7()
    {
        driver.Navigate().GoToUrl("https://automationintesting.online/");
        driver.Manage().Window.Size = new System.Drawing.Size(974, 1040);
        driver.FindElement(By.CssSelector(".btn:nth-child(5)")).Click();
        driver.FindElement(By.CssSelector("button:nth-child(3)")).Click();
        {
            var dragged = driver.FindElement(By.XPath("//button[text()=\'11\']"));
            var dropped = driver.FindElement(By.XPath("//button[text()=\'25\']"));
            Actions builder = new Actions(driver);
            builder.DragAndDrop(dragged, dropped).Perform();
        }
        Thread.Sleep(2000);
        driver.FindElement(By.Name("firstname")).Click();
        driver.FindElement(By.Name("firstname")).SendKeys("Test");
        driver.FindElement(By.Name("lastname")).SendKeys("Test");
        driver.FindElement(By.Name("email")).SendKeys("test@test.com");
        driver.FindElement(By.Name("phone")).SendKeys("061-123-456");
        driver.FindElement(By.CssSelector(".btn:nth-child(6)")).Click();
        var successButton = driver.FindElement(By.CssSelector(".btn:nth-child(1)"));
        successButton.Click();
        Thread.Sleep(4000);
        var success = driver.FindElement(By.XPath("//*[contains(text(), 'Booking Successful!')]"));
        Thread.Sleep(4000);
    }
}
